import { CONTRACTS, type ContractDef, type ContractKind } from './universe';

/** Authoritative reservoir/lifecycle model. Red/2nd-Red are privileged evidence, not the reservoir definition. */
export type ReservoirKind='PSYCHOLOGICAL'|'CONCENTRATION'|'TRANSITION'|'COMPOSITE';
export type Lifecycle='NO_LIQUIDITY'|'FORMING'|'BUILDING'|'MATURE'|'EXHAUSTION_WATCH'|'EXHAUSTION_CONFIRMED'|'DELIVERY'|'DELIVERY_ACCELERATING'|'ABSORBING'|'RELEASE_WATCH'|'RELEASE'|'RIPE'|'CONFIRMED'|'CONFLICTED'|'BLOCKED';
export interface ReservoirEvidence { digit:number; kind:ReservoirKind; score:number; persistence:number; concentration:number; pressure:number; coherence:number; sentinelRole:'RED'|'SECOND_RED'|'PURPLE'|'GREEN'|'SECOND_GREEN'|'NONE'; }
export interface AuthoritativeContract { id:string; label:string; kind:ContractKind; barrier:number; state:Lifecycle; liquidityLevel:number; accumulatedLiquidity:number; reservoirScore:number; reservoirDigits:number[]; reservoirs:ReservoirEvidence[]; maturity:number; exhaustion:number; delivery:number; absorption:number; release:number; confirmation:number; conflict:number; psychologyValid:boolean; psychology:{green:number;secondGreen:number;red:number;secondRed:number;purple:number|null}; vetoes:string[]; age:number; trajectory:'STRENGTHENING'|'STABLE'|'WEAKENING'|'CONFLICTED'; }
export interface AuthoritativeMarket { symbol:string; sample:number; contracts:AuthoritativeContract[]; top:AuthoritativeContract; bestQualified:AuthoritativeContract|null; }

const clamp=(x:number,a=0,b=100)=>Math.max(a,Math.min(b,x));
const avg=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const freq=(ds:number[])=>{const c=Array(10).fill(0);for(const d of ds)if(d>=0&&d<=9)c[d]++;const n=Math.max(1,ds.length);return c.map(x=>x/n)};
const rate=(ds:number[],d:number,w:number)=>{const x=ds.slice(-Math.min(w,ds.length));return x.filter(v=>v===d).length/Math.max(1,x.length)};
const slope=(a:number[])=>{if(a.length<4)return 0;const m=avg(a),x=(a.length-1)/2,den=a.reduce((s,_,i)=>s+(i-x)**2,0)||1;return a.reduce((s,y,i)=>s+(i-x)*(y-m),0)/den};
const entropy=(p:number[])=>-p.reduce((s,x)=>s+(x>0?x*Math.log2(x):0),0)/Math.log2(10);

function psychology(ds:number[],kind:ContractKind,barrier:number){
 const x=ds.slice(-1000),p=freq(x),h=Math.max(1,Math.floor(x.length/2)),a=freq(x.slice(0,h)),b=freq(x.slice(h));
 const pressure=p.map((_,d)=>(b[d]??0)-(a[d]??0));const order=[0,1,2,3,4,5,6,7,8,9].sort((u,v)=>p[v]-p[u]||u-v);const green=order[0],secondGreen=order[1],red=order[9],secondRed=order[8];
 let purple:number|null=null;for(let d=0;d<10;d++)if(pressure[d]>.005&&(purple===null||pressure[d]>pressure[purple]))purple=d;
 const winners=[...Array(10).keys()].filter(d=>kind==='OVER'?d>barrier:d<barrier),losers=[...Array(10).keys()].filter(d=>!winners.includes(d));const reasons:string[]=[];const bars=[green,secondGreen,red,secondRed,...(purple===null?[]:[purple])];
 if(bars.filter(d=>losers.includes(d)).length>2)reasons.push('3+ Sentinel bars are on the losing side');if(losers.includes(red))reasons.push(`Red d${red} is losing-side`);if(losers.includes(secondRed))reasons.push(`2nd Red d${secondRed} is losing-side`);if(losers.includes(secondGreen))reasons.push(`2nd Green d${secondGreen} is losing-side`);if(purple!==null&&losers.includes(purple))reasons.push(`Purple d${purple} is losing-side`);
 if(winners.includes(green)){if(kind==='UNDER'&&green%2===0)reasons.push(`UNDER Green d${green} must be odd`);if(kind==='OVER'&&green%2!==0)reasons.push(`OVER Green d${green} must be even`);}if(winners.includes(red)){if(kind==='UNDER'&&(red%2!==0||red===8))reasons.push(`UNDER Red d${red} must be even and never 8`);if(kind==='OVER'&&(red%2===0||red===1))reasons.push(`OVER Red d${red} must be odd and never 1`);}
 if(kind==='UNDER'&&p[9]>=.105&&pressure[9]>.005)reasons.push('UNDER d9 is elevated and still increasing');if(kind==='OVER'&&p[0]>=.105&&pressure[0]>.005)reasons.push('OVER d0 is elevated and still increasing');
 return {p,pressure,green,secondGreen,red,secondRed,purple,winners,losers,valid:x.length>=1000&&reasons.length===0,reasons};
}

function reservoirEvidence(ds:number[],c:ContractDef,p:ReturnType<typeof psychology>):ReservoirEvidence[]{
 const median=[...p.p].sort((a,b)=>a-b)[5]??.1;
 return p.winners.map(d=>{const r20=rate(ds,d,20),r60=rate(ds,d,60),r120=rate(ds,d,120),r500=rate(ds,d,500),r1000=rate(ds,d,1000);const concentration=clamp((median-p.p[d])*900+50);const persistence=clamp([r20,r60,r120,r500,r1000].filter(v=>v>0).length*20);const pressure=clamp(50+p.pressure[d]*3500);const coherence=clamp(50+(r120-r500)*1200+(r60-r500)*900+(r20-r500)*500);const transition=clamp(50+(r20-r500)*1800+(r60-r500)*1000);const red=d===p.red,secondRed=d===p.secondRed,purple=d===p.purple,green=d===p.green,secondGreen=d===p.secondGreen;let score=concentration*.25+persistence*.2+pressure*.15+coherence*.2+transition*.2;if(red)score+=18;if(secondRed)score+=12;if(purple)score+=8;if(green&&p.pressure[d]>=0)score-=18;if(green&&p.pressure[d]<0)score+=8;const kind:ReservoirKind=(red||secondRed)?(purple||transition>65?'COMPOSITE':'PSYCHOLOGICAL'):(transition>70?'TRANSITION':concentration>65?'CONCENTRATION':'COMPOSITE');return {digit:d,kind,score:clamp(score),persistence,concentration,pressure,coherence,sentinelRole:red?'RED':secondRed?'SECOND_RED':purple?'PURPLE':green?'GREEN':secondGreen?'SECOND_GREEN':'NONE'};}).filter(e=>e.score>=42).sort((a,b)=>b.score-a.score).slice(0,4);
}

function contract(ds:number[],c:ContractDef,previous?:AuthoritativeContract):AuthoritativeContract{
 const p=psychology(ds,c.kind,c.barrier),reservoirs=reservoirEvidence(ds,c,p),reservoirScore=reservoirs.length?avg(reservoirs.map(r=>r.score)):0,dominant=[p.green,p.secondGreen];const domDecay=avg(dominant.map(d=>clamp(55-slope([rate(ds,d,500),rate(ds,d,240),rate(ds,d,120),rate(ds,d,60),rate(ds,d,20)])*12000)));const exhaustion=clamp(domDecay+p.pressure.filter((v,d)=>p.losers.includes(d)&&v<0).length*8);const delivery=clamp(avg(reservoirs.map(r=>35+(rate(ds,r.digit,20)-rate(ds,r.digit,120))*2600+(rate(ds,r.digit,60)-rate(ds,r.digit,240))*1400+r.pressure*.2)));const migration=clamp(avg(reservoirs.map(r=>r.coherence)));const absorption=clamp(delivery*.4+exhaustion*.35+migration*.25);const release=clamp(exhaustion*.35+delivery*.35+migration*.2+absorption*.1);const entropyShift=clamp(Math.abs(entropy(freq(ds.slice(-20)))-entropy(freq(ds.slice(-120))))*180);const conflict=clamp((p.valid?0:35)+Math.max(0,55-migration)*.5+entropyShift*.35);
 const maturity=clamp(reservoirScore*.55+avg(reservoirs.map(r=>r.persistence))*.2+migration*.25);const accumulated=clamp(reservoirScore*.45+avg(reservoirs.map(r=>r.persistence))*.25+avg(reservoirs.map(r=>r.coherence))*.2+Math.min(ds.length,1000)/10*.1);const liquidity=clamp(accumulated*.55+maturity*.2+Math.max(exhaustion,delivery,absorption)*.25);const confirmation=clamp(reservoirScore*.18+maturity*.15+exhaustion*.18+delivery*.2+absorption*.12+release*.12+(100-conflict)*.05);const vetoes=[...p.reasons];if(!reservoirs.length)vetoes.push('No persistent winning-side reservoir evidence');if(accumulated<45)vetoes.push('Reservoir accumulation below qualification threshold');const mature=(previous?.age??0)>=12;const qualified=p.valid&&mature&&accumulated>=65&&maturity>=62&&exhaustion>=65&&delivery>=62&&conflict<60&&vetoes.length===0;
 let state:Lifecycle='NO_LIQUIDITY';if(accumulated>=35)state='FORMING';if(accumulated>=50)state='BUILDING';if(maturity>=62)state='MATURE';if(exhaustion>=62)state='EXHAUSTION_WATCH';if(exhaustion>=75)state='EXHAUSTION_CONFIRMED';if(delivery>=62)state='DELIVERY';if(delivery>=80&&migration>=65)state='DELIVERY_ACCELERATING';if(absorption>=72)state='ABSORBING';if(release>=76)state='RELEASE_WATCH';if(release>=82&&maturity>=70)state='RELEASE';if(qualified)state='CONFIRMED';if(conflict>=82)state='CONFLICTED';if(!p.valid&&p.reasons.length>=3)state='BLOCKED';const trajectory:AuthoritativeContract['trajectory']=conflict>=70?'CONFLICTED':liquidity>(previous?.liquidityLevel??liquidity)+2?'STRENGTHENING':liquidity<(previous?.liquidityLevel??liquidity)-2?'WEAKENING':'STABLE';
 return {id:c.id,label:c.label,kind:c.kind,barrier:c.barrier,state,liquidityLevel:liquidity,accumulatedLiquidity:accumulated,reservoirScore,reservoirDigits:reservoirs.map(r=>r.digit),reservoirs,maturity,exhaustion,delivery,absorption,release,confirmation,conflict,psychologyValid:p.valid,psychology:{green:p.green,secondGreen:p.secondGreen,red:p.red,secondRed:p.secondRed,purple:p.purple},vetoes,age:(previous?.age??0)+1,trajectory};
}

export function analyzeAuthoritativeMarket(symbol:string,history:{d:number}[],previous?:AuthoritativeMarket):AuthoritativeMarket{const ds=history.map(t=>t.d).slice(-1000);const contracts=CONTRACTS.map(c=>contract(ds,c,previous?.contracts.find(x=>x.id===c.id)));const sorted=[...contracts].sort((a,b)=>b.confirmation-a.confirmation||b.liquidityLevel-a.liquidityLevel);return {symbol,sample:ds.length,contracts,top:sorted[0],bestQualified:sorted.find(c=>c.state==='CONFIRMED')??null};}
